background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 7
    brightness = 0.5
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 1
    outer_color = rgb(54546d)
    inner_color = rgb(1a1a22)
    font_color = rgb(c5c9c5)
    fade_on_empty = true
    placeholder_text = <i>Password</i>
    check_color = rgb(7e9cd8)
    fail_color = rgb(c34043)
    fail_text = <i>Wrong password</i>
    dots_spacing = 0.3
    dots_center = true
    position = 0, -80
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = rgba(c5c9c5ff)
    font_size = 64
    font_family = JetBrainsMono Nerd Font
    position = 0, 100
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%A, %d %B")"
    color = rgba(54546dff)
    font_size = 18
    font_family = JetBrainsMono Nerd Font
    position = 0, 20
    halign = center
    valign = center
}
